### ISSUE TITLE
Home Assistant Log - error adding entities

### ISSUE THREAD

**Issue by headbouyJB** [Neflardio/growatt-custom-component#1]
Hi!
I've added your custom component that seems to handle my hybrid inverter pretty well. 
However, it doesn't seem to update the sensors regularly - the figures update when I restart, and that's it. 

I'm not sure if this is related, but there is an error in my logs as noted below;

> Logger: homeassistant.components.sensor
> Source: custom_components/growatt/sensor.py:818 
> Integration: Sensor (documentation, issues) 
> First occurred: 7:21:07 PM (2 occurrences) 
> Last logged: 7:21:07 PM
> 
> Error adding entities for domain sensor with platform growatt
> Error while setting up growatt platform for sensor
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
>     await entity.add_to_platform_finish()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
>     sstate = self.state
>   File "/config/custom_components/growatt/sensor.py", line 818, in state
>     result = round(result, round_to)
> TypeError: type NoneType doesn't define __round__ method

Copying from line 812 to 819 of sensor.py;

`    @property
    def state(self):
        """Return the state of the sensor."""
        result = self.probe.get_data(SENSOR_TYPES[self.sensor][2])
        round_to = SENSOR_TYPES[self.sensor][3].get("round")
        if round_to is not None:
            result = round(result, round_to)
        return result`

**Comment by headbouyJB** [comment]
Commenting out lines 817 and 818 allows the sensors to refresh, but they're doing so at 10 minute intervals.
